# Демо-блокнот к Лекции №2. sklearn-api

In [4]:
import numpy as np 
import pandas as pd

In [5]:
df = pd.read_excel(r'D:\Datasets\Telco_customer_churn.xlsx', sheet_name='Telco_Churn')
df

CustomerID  Count        Country       State          City  Zip Code  \
0     3668-QPYBK      1  United States  California   Los Angeles     90003   
1     9237-HQITU      1  United States  California   Los Angeles     90005   
2     9305-CDSKC      1  United States  California   Los Angeles     90006   
3     7892-POOKP      1  United States  California   Los Angeles     90010   
4     0280-XJGEX      1  United States  California   Los Angeles     90015   
...          ...    ...            ...         ...           ...       ...   
7038  2569-WGERO      1  United States  California       Landers     92285   
7039  6840-RESVB      1  United States  California      Adelanto     92301   
7040  2234-XADUH      1  United States  California         Amboy     92304   
7041  4801-JZAZL      1  United States  California  Angelus Oaks     92305   
7042  3186-AJIEK      1  United States  California  Apple Valley     92308   

                    Lat Long   Latitude   Longitude  Gender  ...  \
0     33.964131, -118.272783  33.964131 -118.272783    Male  ...   
1      34.059281, -118.30742  34.059281 -118.307420  Female  ...   
2     34.048013, -118.293953  34.048013 -118.293953  Female  ...   
3     34.062125, -118.315709  34.062125 -118.315709  Female  ...   
4     34.039224, -118.266293  34.039224 -118.266293    Male  ...   
...                      ...        ...         ...     ...  ...   
7038  34.341737, -116.539416  34.341737 -116.539416  Female  ...   
7039  34.667815, -117.536183  34.667815 -117.536183    Male  ...   
7040  34.559882, -115.637164  34.559882 -115.637164  Female  ...   
7041     34.1678, -116.86433  34.167800 -116.864330  Female  ...   
7042  34.424926, -117.184503  34.424926 -117.184503    Male  ...   

            Contract Paperless Billing             Payment Method  \
0     Month-to-month               Yes               Mailed check   
1     Month-to-month               Yes           Electronic check   
2     Month-to-month               Yes           Electronic check   
3     Month-to-month               Yes           Electronic check   
4     Month-to-month               Yes  Bank transfer (automatic)   
...              ...               ...                        ...   
7038        Two year               Yes  Bank transfer (automatic)   
7039        One year               Yes               Mailed check   
7040        One year               Yes    Credit card (automatic)   
7041  Month-to-month               Yes           Electronic check   
7042        Two year               Yes  Bank transfer (automatic)   

      Monthly Charges Total Charges Churn Label Churn Value Churn Score  CLTV  \
0               53.85        108.15         Yes           1          86  3239   
1               70.70        151.65         Yes           1          67  2701   
2               99.65         820.5         Yes           1          86  5372   
3              104.80       3046.05         Yes           1          84  5003   
4              103.70        5036.3         Yes           1          89  5340   
...               ...           ...         ...         ...         ...   ...   
7038            21.15        1419.4          No           0          45  5306   
7039            84.80        1990.5          No           0          59  2140   
7040           103.20        7362.9          No           0          71  5560   
7041            29.60        346.45          No           0          59  2793   
7042           105.65        6844.5          No           0          38  5097   

                       Churn Reason  
0      Competitor made better offer  
1                             Moved  
2                             Moved  
3                             Moved  
4     Competitor had better devices  
...                             ...  
7038                            NaN  
7039                            NaN  
7040                            NaN  
7041                            NaN  
7042                            

## Что такое sklearn?

`Scikit-learn` - это библиотека машинного обучения с открытым исходным кодом, которая поддерживает контролируемое и неконтролируемое обучение. Она также предоставляет различные инструменты для подгонки моделей, предварительной обработки данных, выбора моделей, оценки моделей и многие другие утилиты.

[Установка библиотеки](https://scikit-learn.org/stable/install.html)

In [6]:
#!pip install -U scikit-learn

In [7]:
import sklearn

Однако дальше нас будет интересовать конкретные сабмодули библиотеки, например, `sklearn.neighbors` или `sklearn.linear_model`

## Что такое sklearn transformers?

In [8]:
class ExampleDataTransformer():
    def fit(self, X, y=None):
        # Узнать параметры для трансформации
        return self

    def transform(self, X):
        # Применить преобразование к данным
        return X
    
    def fit_transform(self, X, y=None):
        self.fit(X, y)
        return self.transform(X)

Как в таком случае будет выглядеть реализация min-max масштабирования?

In [9]:
class CustomMinMaxScaler:
    def __init__(self):
        self.min_value = None
        self.max_value = None

    def fit(self, X, y=None):
        self.max_value = X.max()
        self.min_value = X.min()
        return self
    
    def transform(self, X):
        if self.min_value is None or self.max_value is None:
            raise ValueError("Неизвестно минимальное или максимальное значение.")
        return (X - self.min_value) / (self.max_value - self.min_value)
    
    def fit_transform(self, X, y=None):
        return self.fit(X, y).transform(X)

In [10]:
minmaxscaler = CustomMinMaxScaler()
minmaxscaler

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CustomerID         7043 non-null   object 
 1   Count              7043 non-null   int64  
 2   Country            7043 non-null   object 
 3   State              7043 non-null   object 
 4   City               7043 non-null   object 
 5   Zip Code           7043 non-null   int64  
 6   Lat Long           7043 non-null   object 
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object 
 10  Senior Citizen     7043 non-null   object 
 11  Partner            7043 non-null   object 
 12  Dependents         7043 non-null   object 
 13  Tenure Months      7043 non-null   int64  
 14  Phone Service      7043 non-null   object 
 15  Multiple Lines     7043 non-null   object 
 16  Internet Service   7043 

In [12]:
df['CLTV'].describe()

count    7043.000000
mean     4400.295755
std      1183.057152
min      2003.000000
25%      3469.000000
50%      4527.000000
75%      5380.500000
max      6500.000000
Name: CLTV, dtype: float64

In [13]:
df['CLTV'] = minmaxscaler.fit_transform(X=df['CLTV'])
df['CLTV'].describe()

count    7043.000000
mean        0.533088
std         0.263077
min         0.000000
25%         0.325995
50%         0.561263
75%         0.751056
max         1.000000
Name: CLTV, dtype: float64

## Не изобретаем велосипеды

[Реализацию](https://github.com/scikit-learn/scikit-learn/blob/c5497b7f7/sklearn/preprocessing/_data.py#L295) того же Min-Max Scaler мы сможем найти в этой библиотеке

In [14]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
print(scaler.fit(data))
print(scaler.data_max_)
print(scaler.transform(data))
print(scaler.transform([[2, 2]]))

MinMaxScaler()
[ 1. 18.]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
[[1.5 0. ]]


Как и другие популярные и часто применяемые обработчики данных.

[Стандартизация:](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html)

In [15]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))
print(scaler.mean_)
print(scaler.transform(data))
print(scaler.transform([[2, 2]]))

StandardScaler()
[0.5 0.5]
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]
[[3. 3.]]


In [16]:
df['Churn Score'].describe()

count    7043.000000
mean       58.699418
std        21.525131
min         5.000000
25%        40.000000
50%        61.000000
75%        75.000000
max       100.000000
Name: Churn Score, dtype: float64

In [14]:
scaler.fit_transform(df['Churn Score'].to_numpy().reshape(-1, 1))

array([[ 1.26840208],
       [ 0.38565022],
       [ 1.26840208],
       ...,
       [ 0.57149272],
       [ 0.01396523],
       [-0.96170787]], shape=(7043, 1))

Почему sklearn требует от нас преобразовывать входные данные в 2D массивы?
Это связано с тем, что многие алгоритмы машинного обучения ожидают, что входные данные будут представлены в виде двумерного массива, где строки соответствуют образцам, а столбцы - признакам.

Посмотрим на то, как может быть реализована модельная kNN-импутация с помощью sklearn

In [20]:
import numpy as np
from sklearn.impute import KNNImputer


X = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=2)
imputer.fit_transform(X)

array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])

## Не только sklearn

Благодаря унифированному интерфейсу любой разработчик может создать свои обработчики данных и использовать их в рамках единого пространств, "неймспейса", "экосистеме". 

Например, существует библиотека feature-engine, не входящая в sklearn, но использующая тот же интерфейс и предлагающая интересные обработчики данных (и не только).

In [15]:
from feature_engine.encoding import CountFrequencyEncoder
X = pd.DataFrame(dict(x1 = [1,2,3,4], x2 = ["c", "a", "b", "c"]))


In [16]:
cf = CountFrequencyEncoder(encoding_method='frequency')
cf.fit(X)

CountFrequencyEncoder(encoding_method='frequency')

In [17]:
cf.transform(X)

x1    x2
0   1  0.50
1   2  0.25
2   3  0.25
3   4  0.50

In [18]:
df[['Internet Service', 'Online Security']]

Internet Service      Online Security
0                 DSL                  Yes
1         Fiber optic                   No
2         Fiber optic                   No
3         Fiber optic                   No
4         Fiber optic                   No
...               ...                  ...
7038               No  No internet service
7039              DSL                  Yes
7040      Fiber optic                   No
7041              DSL                  Yes
7042      Fiber optic                  Yes

[7043 rows x 2 columns]

In [19]:
df[['Internet Service', 'Online Security']].describe()

Internet Service Online Security
count              7043            7043
unique                3               3
top         Fiber optic              No
freq               3096            3498

In [20]:
cf.fit_transform(df[['Internet Service', 'Online Security']])

Internet Service  Online Security
0             0.343746         0.286668
1             0.439585         0.496663
2             0.439585         0.496663
3             0.439585         0.496663
4             0.439585         0.496663
...                ...              ...
7038          0.216669         0.216669
7039          0.343746         0.286668
7040          0.439585         0.496663
7041          0.343746         0.286668
7042          0.439585         0.286668

[7043 rows x 2 columns]

## Объединяем все в пайплайн

https://habr.com/ru/companies/yandex_praktikum/articles/756474/

In [21]:
from sklearn.compose import ColumnTransformer

from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error

### Для числовых признаков

In [ ]:
simple_imputer = SimpleImputer(strategy='median')
std_scaler = StandardScaler()

pipe_num = Pipeline(
    [('imputer', simple_imputer), ('scaler', std_scaler)]
)

Проверим работу пайплайна

In [26]:
pipe_num.get_feature_names_out()

array(['Count', 'Zip Code', 'Latitude', 'Longitude', 'Tenure Months',
       'Monthly Charges', 'Churn Value', 'Churn Score', 'CLTV'],
      dtype=object)

In [24]:
pipe_num.fit_transform(df.select_dtypes(include=['number']))

array([[ 0.        , -1.8861747 , -0.94411111, ...,  1.66382851,
         1.26840208, -0.98167549],
       [ 0.        , -1.8851027 , -0.90536213, ...,  1.66382851,
         0.38565022, -1.4364618 ],
       [ 0.        , -1.8845667 , -0.90995092, ...,  1.66382851,
         1.26840208,  0.82140853],
       ...,
       [ 0.        , -0.65283239, -0.70149686, ..., -0.60102348,
         0.57149272,  0.98033014],
       [ 0.        , -0.65229639, -0.86116874, ..., -0.60102348,
         0.01396523, -1.35869165],
       [ 0.        , -0.65068838, -0.75645648, ..., -0.60102348,
        -0.96170787,  0.58894341]], shape=(7043, 9))

Не очень понятно, что у нас получилось! Пайплайны возвращают массивы numpy. Чтобы вызвать удобные функцию типа .info() и describe(), превратим это все в датафрейм

In [27]:
gf = pd.DataFrame(
    data=pipe_num.fit_transform(df.select_dtypes(include=['number'])),
    columns=pipe_num.get_feature_names_out()
)
gf

Count  Zip Code  Latitude  Longitude  Tenure Months  Monthly Charges  \
0       0.0 -1.886175 -0.944111   0.707268      -1.236724        -0.362660   
1       0.0 -1.885103 -0.905362   0.691215      -1.236724         0.197365   
2       0.0 -1.884567 -0.909951   0.697457      -0.992402         1.159546   
3       0.0 -1.882423 -0.904204   0.687374      -0.177995         1.330711   
4       0.0 -1.879743 -0.913530   0.710276       0.677133         1.294151   
...     ...       ...       ...        ...            ...              ...   
7038    0.0 -0.663016 -0.790334   1.510595       1.613701        -1.449476   
7039    0.0 -0.654440 -0.657542   1.048644      -0.340876         0.665992   
7040    0.0 -0.652832 -0.701497   1.928742       1.613701         1.277533   
7041    0.0 -0.652296 -0.861169   1.360014      -0.870241        -1.168632   
7042    0.0 -0.650688 -0.756456   1.211630       1.369379         1.358961   

      Churn Value  Churn Score      CLTV  
0        1.663829     1.268402 -0.981675  
1        1.663829     0.385650 -1.436462  
2        1.663829     1.268402  0.821409  
3        1.663829     1.175481  0.509483  
4        1.663829     1.407784  0.794358  
...           ...          ...       ...  
7038    -0.601023    -0.636484  0.765617  
7039    -0.601023     0.013965 -1.910691  
7040    -0.601023     0.571493  0.980330  
7041    -0.601023     0.013965 -1.358692  
7042    -0.601023    -0.961708  0.588943  

[7043 rows x 9 columns]

In [28]:
gf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Count            7043 non-null   float64
 1   Zip Code         7043 non-null   float64
 2   Latitude         7043 non-null   float64
 3   Longitude        7043 non-null   float64
 4   Tenure Months    7043 non-null   float64
 5   Monthly Charges  7043 non-null   float64
 6   Churn Value      7043 non-null   float64
 7   Churn Score      7043 non-null   float64
 8   CLTV             7043 non-null   float64
dtypes: float64(9)
memory usage: 495.3 KB


In [29]:
gf.describe()

Count      Zip Code      Latitude     Longitude  Tenure Months  \
count  7043.0  7.043000e+03  7.043000e+03  7.043000e+03   7.043000e+03   
mean      0.0  2.292138e-15 -1.404338e-15 -1.912806e-15  -1.614182e-17   
std       0.0  1.000071e+00  1.000071e+00  1.000071e+00   1.000071e+00   
min       0.0 -1.887247e+00 -1.517630e+00 -2.086674e+00  -1.318165e+00   
25%       0.0 -7.611049e-01 -9.169139e-01 -9.345592e-01  -9.516817e-01   
50%       0.0  1.609903e-02  4.452595e-02  3.151224e-02  -1.372744e-01   
75%       0.0  9.803680e-01  7.910362e-01  8.136506e-01   9.214551e-01   
max       0.0  1.414530e+00  2.313001e+00  2.598084e+00   1.613701e+00   

       Monthly Charges  Churn Value   Churn Score          CLTV  
count     7.043000e+03  7043.000000  7.043000e+03  7.043000e+03  
mean     -5.649637e-17     0.000000  1.291346e-16 -9.685092e-17  
std       1.000071e+00     1.000071  1.000071e+00  1.000071e+00  
min      -1.545860e+00    -0.601023 -2.494908e+00 -2.026501e+00  
25%      -9.725399e-01    -0.601023 -8.687866e-01 -7.872501e-01  
50%       1.857327e-01    -0.601023  1.068865e-01  1.071066e-01  
75%       8.338335e-01     1.663829  7.573352e-01  8.285938e-01  
max       1.794352e+00     1.663829  1.918851e+00  1.774938e+00

### Для категориальных признаков

In [31]:
s_imputer = SimpleImputer(strategy='constant', fill_value='unknown')
ohe_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

pipe_cat = Pipeline([('imputer', s_imputer), ('encoder', ohe_encoder)])

In [ ]:
pipe_cat.fit_transform(df.select_dtypes(include=['object']))

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['float', 'int', 'str']

Ой! Похоже, `.select_dtypes(include=['object'])` сработал не на отлично. Поглядим на эту выборку:

In [43]:
df.select_dtypes(include=['object'])

CustomerID        Country       State          City  \
0     3668-QPYBK  United States  California   Los Angeles   
1     9237-HQITU  United States  California   Los Angeles   
2     9305-CDSKC  United States  California   Los Angeles   
3     7892-POOKP  United States  California   Los Angeles   
4     0280-XJGEX  United States  California   Los Angeles   
...          ...            ...         ...           ...   
7038  2569-WGERO  United States  California       Landers   
7039  6840-RESVB  United States  California      Adelanto   
7040  2234-XADUH  United States  California         Amboy   
7041  4801-JZAZL  United States  California  Angelus Oaks   
7042  3186-AJIEK  United States  California  Apple Valley   

                    Lat Long  Gender Senior Citizen Partner Dependents  \
0     33.964131, -118.272783    Male             No      No         No   
1      34.059281, -118.30742  Female             No      No        Yes   
2     34.048013, -118.293953  Female             No      No        Yes   
3     34.062125, -118.315709  Female             No     Yes        Yes   
4     34.039224, -118.266293    Male             No      No        Yes   
...                      ...     ...            ...     ...        ...   
7038  34.341737, -116.539416  Female             No      No         No   
7039  34.667815, -117.536183    Male             No     Yes        Yes   
7040  34.559882, -115.637164  Female             No     Yes        Yes   
7041     34.1678, -116.86433  Female             No     Yes        Yes   
7042  34.424926, -117.184503    Male             No      No         No   

     Phone Service  ...    Device Protection         Tech Support  \
0              Yes  ...                   No                   No   
1              Yes  ...                   No                   No   
2              Yes  ...                  Yes                   No   
3              Yes  ...                  Yes                  Yes   
4              Yes  ...                  Yes                   No   
...            ...  ...                  ...                  ...   
7038           Yes  ...  No internet service  No internet service   
7039           Yes  ...                  Yes                  Yes   
7040           Yes  ...                  Yes                   No   
7041            No  ...                   No                   No   
7042           Yes  ...                  Yes                  Yes   

             Streaming TV     Streaming Movies        Contract  \
0                      No                   No  Month-to-month   
1                      No                   No  Month-to-month   
2                     Yes                  Yes  Month-to-month   
3                     Yes                  Yes  Month-to-month   
4                     Yes                  Yes  Month-to-month   
...                   ...                  ...             ...   
7038  No internet service  No internet service        Two year   
7039                  Yes                  Yes        One year   
7040                  Yes                  Yes        One year   
7041                   No                   No  Month-to-month   
7042                  Yes                  Yes        Two year   

     Paperless Billing             Payment Method Total Charges Churn Label  \
0                  Yes               Mailed check        108.15         Yes   
1                  Yes           Electronic check        151.65         Yes   
2                  Yes           Electronic check         820.5         Yes   
3                  Yes           Electronic check       3046.05         Yes   
4                  Yes  Bank transfer (automatic)        5036.3         Yes   
...                ...                        ...           ...         ...   
7038               Yes  Bank transfer (automatic)        1419.4          No   
7039               Yes               Mailed check        1990.5          No   
7040               Yes    Credit card (automatic)  

Видим колонки "Lat Long", "CustomerID" и 'Total Charges'', которые либо не информативны, либо явно не категориальные. Для простоты удалим их из выборки (пока).

In [ ]:
df.drop(columns=['Lat Long', 'CustomerID', 'Total Charges'], inplace=True)

In [48]:
pipe_cat.fit_transform(
    df.select_dtypes(include=['object'])
    )

array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 1., 0., ..., 0., 0., 1.],
       [1., 1., 0., ..., 0., 0., 1.],
       [1., 1., 0., ..., 0., 0., 1.]], shape=(7043, 1193))

### Объединяем пайплайны

Существует несколько способов в рамках одного пайплайн реализовать разветвленную обработку данных, это ColumnTransforfmer и FeatureUnion. Рассмотрим их поочередно

#### FeatureUnion

In [ ]:
from sklearn.pipeline import Pipeline, FeatureUnion

feature_union = FeatureUnion([

])

#### ColumnTransformer

In [50]:
simple_imputer = SimpleImputer(strategy='median')
std_scaler = StandardScaler()

pipe_num = Pipeline([('imputer', simple_imputer), ('scaler', std_scaler)])

s_imputer = SimpleImputer(strategy='constant', fill_value='unknown')
ohe_encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
pipe_cat = Pipeline([('imputer', s_imputer), ('encoder', ohe_encoder)])

col_transformer = ColumnTransformer([('num_preproc', pipe_num, [x for x in df.columns if df[x].dtype!='object']),
                                     ('cat_preproc', pipe_cat, [x for x in df.columns if df[x].dtype=='object'])])

final_pipe = Pipeline([('preproc', col_transformer)])

## Как pipeline применяется при обучении модели?

Вот у нас есть датасет, поглядим на него еще раз

In [51]:
df.head(5)

Count        Country       State         City  Zip Code   Latitude  \
0      1  United States  California  Los Angeles     90003  33.964131   
1      1  United States  California  Los Angeles     90005  34.059281   
2      1  United States  California  Los Angeles     90006  34.048013   
3      1  United States  California  Los Angeles     90010  34.062125   
4      1  United States  California  Los Angeles     90015  34.039224   

    Longitude  Gender Senior Citizen Partner  ... Streaming TV  \
0 -118.272783    Male             No      No  ...           No   
1 -118.307420  Female             No      No  ...           No   
2 -118.293953  Female             No      No  ...          Yes   
3 -118.315709  Female             No     Yes  ...          Yes   
4 -118.266293    Male             No      No  ...          Yes   

   Streaming Movies        Contract Paperless Billing Monthly Charges  \
0                No  Month-to-month               Yes           53.85   
1                No  Month-to-month               Yes           70.70   
2               Yes  Month-to-month               Yes           99.65   
3               Yes  Month-to-month               Yes          104.80   
4               Yes  Month-to-month               Yes          103.70   

  Churn Label Churn Value Churn Score      CLTV                   Churn Reason  
0         Yes           1          86  0.274850   Competitor made better offer  
1         Yes           1          67  0.155215                          Moved  
2         Yes           1          86  0.749166                          Moved  
3         Yes           1          84  0.667111                          Moved  
4         Yes           1          89  0.742050  Competitor had better devices  

[5 rows x 29 columns]

Допустим, таргетом является `CLTV`, выделим его из данных

In [52]:
target = df['CLTV']
features = df.drop(columns=['CLTV'])

Теперь подготовим обучающее и валидационное множества данных:

In [ ]:
train_features, val_features, train_target, val_target = train_test_split(
    features, target, test_size=0.2, random_state=42
)

Теперь мы готовим данные для обучениz, делаем `fit_transform` на обучающих, а на валидационных только `transform`:

In [ ]:
X_train = final_pipe.fit_transform(train_features)
X_val = final_pipe.transform(val_features)